//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionalInfoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutritionalInfoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Features&gt;
        ///  &lt;apple F0=&quot;16305&quot; F1=&quot;16312&quot; F2=&quot;16312&quot; F3=&quot;16312&quot; F4=&quot;16312&quot; F5=&quot;16312&quot; F6=&quot;16312&quot; F7=&quot;16312&quot; F8=&quot;16312&quot; F9=&quot;16312&quot; F10=&quot;16312&quot; F11=&quot;16312&quot; F12=&quot;16312&quot; F13=&quot;16312&quot; F14=&quot;16312&quot; F15=&quot;16312&quot; F16=&quot;16312&quot; F17=&quot;16312&quot; F18=&quot;16312&quot; F19=&quot;16312&quot; F20=&quot;16312&quot; F21=&quot;16312&quot; F22=&quot;16312&quot; F23=&quot;16312&quot; F24=&quot;16312&quot; F25=&quot;16312&quot; F26=&quot;16312&quot; F27=&quot;16312&quot; F28=&quot;16312&quot; F29=&quot;16312&quot; F30=&quot;16312&quot; F31=&quot;16312&quot; F32=&quot;16312&quot; F33=&quot;16320&quot; F34=&quot;16320&quot; F35=&quot;16320&quot; F36=&quot;16320&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrainingSamples {
            get {
                return ResourceManager.GetString("TrainingSamples", resourceCulture);
            }
        }
    }
}
